const { test, expect } = require('@playwright/test');
const { randomUUID } = require('node:crypto');
test.use({ actionTimeout: 15000 });

test('employee creates a ticket and Help Desk completes the Fiori workflow', async ({ page, request }) => {
  const tenant = `browser-${randomUUID()}`;
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => {
    if (message.type() === 'error' && /FormatException|TypeError|ReferenceError/.test(message.text())) errors.push(message.text());
  });
  await page.route('**/odata/v4/it-operations/**', route => {
    const url = new URL(route.request().url());
    url.searchParams.set('sap-client', tenant);
    return route.continue({ url: url.toString() });
  });
  await page.goto('/test/flp.html#app-preview', { waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'My IT Support', exact: true }).click({ timeout: 90000 });
  await expect(page).toHaveURL(/MySupport/);
  const create = page.getByRole('button', { name: 'Create ticket', exact: true });
  await expect(create).toBeEnabled();
  await create.click();
  await expect(page.getByText('Enter a subject and description before creating the ticket.', { exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'Subject', exact: true }).fill('Intermittent laptop display failure');
  await page.getByRole('textbox', { name: 'Description', exact: true }).fill('The display goes black after signing in and returns after reconnecting the charger.');
  await page.getByRole('combobox', { name: 'Affected asset', exact: true }).press('F4');
  await page.getByRole('option', { name: 'IT-LAP-00452', exact: true }).click();
  await create.click();
  await expect(page).toHaveURL(/Tickets\(/, { timeout: 30000 });
  await expect(page.getByRole('button', { name: 'Submit ticket', exact: true })).toBeVisible();
  const ticketURL = page.url();
  const ticketUUID = ticketURL.match(/Tickets\(([^)]+)\)/)[1];
  await page.getByRole('button', { name: 'View requester', exact: true }).click();
  await expect(page).toHaveURL(/\/Requester/);
  await expect(page.getByText('ayesha.khan@example.test', { exact: true })).toBeVisible();
  await page.goBack();
  await page.getByRole('button', { name: 'View asset', exact: true }).click();
  await expect(page).toHaveURL(/\/Asset/);
  await expect(page.getByText('Latitude 5440', { exact: true }).filter({ visible: true }).first()).toBeVisible();
  await page.goBack();
  await page.getByRole('button', { name: 'Submit ticket', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Assign technician', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Assign technician', exact: true }).click();
  const assignDialog = page.getByRole('dialog');
  await assignDialog.getByRole('textbox', { name: /Technician/ }).fill('00000001-0000-4000-8000-000000000004');
  await assignDialog.getByRole('button', { name: 'Assign technician', exact: true }).click();
  await expect(assignDialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Start work', exact: true }).click();
  await page.getByRole('button', { name: 'Resolve ticket', exact: true }).click();
  const resolveDialog = page.getByRole('dialog');
  await resolveDialog.getByRole('textbox', { name: /Resolution/ }).fill('Replaced the charger and verified the display through three restart cycles.');
  await resolveDialog.getByRole('button', { name: 'Resolve ticket', exact: true }).click();
  await expect(resolveDialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Confirm and close', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Overview', exact: true }).getByText('CLOSED', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Submit ticket', exact: true })).toHaveCount(0);
  const response = await request.get(`/odata/v4/it-operations/Tickets(${ticketUUID})?$expand=History&sap-client=${tenant}`);
  expect(response.ok()).toBeTruthy();
  const ticket = await response.json();
  expect(ticket.Status).toBe('CLOSED');
  expect(ticket.History.map(event => event.Action)).toEqual(['Create', 'Submit', 'AssignTechnician', 'StartWork', 'Resolve', 'Close']);
  await page.getByRole('button', { name: 'Help Desk', exact: true }).click();
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await expect(page.getByText('Intermittent laptop display failure', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/phase-3-help-desk.png' });
  expect(errors).toEqual([]);
});
